version: "3.7"

services:
  db:
    image: mysql
    container_name: ${PROJECT_NAME}-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PROJECT_NAME}
      MYSQL_USER: ${PROJECT_NAME}
      MYSQL_PASSWORD: ${PROJECT_NAME}
      MYSQL_DATABASE: ${PROJECT_NAME}
    ports:
      - ${MYSQL_PORT}:3306

  web:
    image: nginx
    container_name: ${PROJECT_NAME}-web
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${SRC_ROOT}:/app
      - ./nginx/sites/${ENV}.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/${ENV}.default.conf:/etc/nginx/${ENV}.default.conf
    links:
      - php
    
  php:
    build: ../
    container_name: ${PROJECT_NAME}-php
    restart: always
    working_dir: /app
    volumes:
      - ${SRC_ROOT}:/app
      - ${SSH_PATH}:/root/.ssh
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    links:
      - db
    environment: 
      MYSQL_PORT: ${MYSQL_PORT}
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
      TEST_RUNTIME_PATH: /tmp/runtime

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80